[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  environment = { VITE_API_URL = "https://ai-resume-creator-backend.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
